simplify script

diff --git a/batchenc b/batchenc
--- a/batchenc
+++ b/batchenc
@@ -11,8 +11,9 @@ elif [ "$3" = flac ]; then
     export CODEC="flac"
 else
     echo "Syntax: batchenc INPUTDIR OUTPUTDIR {opus,ogg,flac,mp3}"
-    exit
+    exit 1
 fi
+
 read -p "Source directory is \""$1"\". Is this correct? > " yn
 case $yn in
     [Yy]* ) : ;;
@@ -28,39 +29,34 @@ case $yn in
 esac
 
 
-# create directory lists
-cd "$1"
-sourcedirs="$(find . -type d -name "*")"
-cd "$2"
-targetdirs="$(find . -type d -name "*")"
+OPWD="$PWD"
+inputDir=$(echo "$1" | sed 's/\/$//')
+outputDir=$(echo "$2" | sed 's/\/$//')
 
-# clean up target directory
-if [[ "$sourcedirs" == "$targetdirs" ]]; then
-    echo "Nothing to do..."
-    exit
+if [ ! -d "$inputDir" ]; then
+  echo "Error: $inputDir: no such directory" 1>&2
+  exit 1
+elif [ ! -d "$outputDir" ]; then
+  echo "Error: $outputDir: no such directory" 1>&2
+  exit 1
 fi
 
-printf %s "$targetdirs" | while read -r line; do
-    cd "$1"
-    if [[ ! -d "${line}" ]]; then
-        echo ""${line}" not in source tree, deleting..."
-        cd "$2"
-        rm -fr "${line}"
-    fi
-done
+cd "$outputDir"
+while IFS= read -d $'\0' directory; do
+  if [ ! -d "${inputDir}/${directory}" ]; then
+    echo "Deleting \"${outputDir}/${directory}\""
+    rm -rf "${outputDir}/${directory}"
+  fi
+done < <( find . -type d -print0 2>/dev/null )
 
+cd "$inputDir"
+while IFS= read -d $'\0' directory; do
+  if [ ! -d "${outputDir}/${directory}" ]; then
+    ls "${directory}"/*.flac >/dev/null 2>&1 || continue
+    echo "Transcoding \"${directory}\""
+    # transcode to CODEC
+    caudec -O "${outputDir}/${directory}" -K -s -c $CODEC "${directory}"/*.flac
+  fi
+done < <( find . -type d -print0 2>/dev/null )
 
-# create directory list
-cd "$1"
-sourcedirs="$(find . -type d -name "*" -print0 | while read -d $'\0' a; do echo "$a"; done)"
-
-# check if target is missing directories
-printf %s "$sourcedirs" | while read -r line; do
-    cd $2
-    if [[ ! -d "${line}" ]]; then
-        echo "Transcoding "${line}""
-
-        # transcode to CODEC
-        caudec -O "${line}" -K -s -c $CODEC "$1""${line}"/*.flac
-    fi
-done
+cd "$OPWD"
